// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: equipment_ai.proto

package genprotos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EquipmentAI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	AmmoType      string                 `protobuf:"bytes,3,opt,name=ammo_type,json=ammoType,proto3" json:"ammo_type,omitempty"`
	UsageTutorial []*UsageTutorialStepAI `protobuf:"bytes,4,rep,name=usage_tutorial,json=usageTutorial,proto3" json:"usage_tutorial,omitempty"`
}

func (x *EquipmentAI) Reset() {
	*x = EquipmentAI{}
	if protoimpl.UnsafeEnabled {
		mi := &file_equipment_ai_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EquipmentAI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentAI) ProtoMessage() {}

func (x *EquipmentAI) ProtoReflect() protoreflect.Message {
	mi := &file_equipment_ai_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentAI.ProtoReflect.Descriptor instead.
func (*EquipmentAI) Descriptor() ([]byte, []int) {
	return file_equipment_ai_proto_rawDescGZIP(), []int{0}
}

func (x *EquipmentAI) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EquipmentAI) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EquipmentAI) GetAmmoType() string {
	if x != nil {
		return x.AmmoType
	}
	return ""
}

func (x *EquipmentAI) GetUsageTutorial() []*UsageTutorialStepAI {
	if x != nil {
		return x.UsageTutorial
	}
	return nil
}

type UsageTutorialStepAI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StepNumber string `protobuf:"bytes,1,opt,name=step_number,json=stepNumber,proto3" json:"step_number,omitempty"`
	Step       string `protobuf:"bytes,2,opt,name=step,proto3" json:"step,omitempty"`
}

func (x *UsageTutorialStepAI) Reset() {
	*x = UsageTutorialStepAI{}
	if protoimpl.UnsafeEnabled {
		mi := &file_equipment_ai_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsageTutorialStepAI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageTutorialStepAI) ProtoMessage() {}

func (x *UsageTutorialStepAI) ProtoReflect() protoreflect.Message {
	mi := &file_equipment_ai_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageTutorialStepAI.ProtoReflect.Descriptor instead.
func (*UsageTutorialStepAI) Descriptor() ([]byte, []int) {
	return file_equipment_ai_proto_rawDescGZIP(), []int{1}
}

func (x *UsageTutorialStepAI) GetStepNumber() string {
	if x != nil {
		return x.StepNumber
	}
	return ""
}

func (x *UsageTutorialStepAI) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

type EquipmentRequestAI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prompt string `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
}

func (x *EquipmentRequestAI) Reset() {
	*x = EquipmentRequestAI{}
	if protoimpl.UnsafeEnabled {
		mi := &file_equipment_ai_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EquipmentRequestAI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentRequestAI) ProtoMessage() {}

func (x *EquipmentRequestAI) ProtoReflect() protoreflect.Message {
	mi := &file_equipment_ai_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentRequestAI.ProtoReflect.Descriptor instead.
func (*EquipmentRequestAI) Descriptor() ([]byte, []int) {
	return file_equipment_ai_proto_rawDescGZIP(), []int{2}
}

func (x *EquipmentRequestAI) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type ThreatData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Location string `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Time     string `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Details  string `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
}

func (x *ThreatData) Reset() {
	*x = ThreatData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_equipment_ai_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ThreatData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreatData) ProtoMessage() {}

func (x *ThreatData) ProtoReflect() protoreflect.Message {
	mi := &file_equipment_ai_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreatData.ProtoReflect.Descriptor instead.
func (*ThreatData) Descriptor() ([]byte, []int) {
	return file_equipment_ai_proto_rawDescGZIP(), []int{3}
}

func (x *ThreatData) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *ThreatData) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *ThreatData) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

type ThreatAssessmentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ThreatLevel        string   `protobuf:"bytes,1,opt,name=threat_level,json=threatLevel,proto3" json:"threat_level,omitempty"`
	RecommendedActions []string `protobuf:"bytes,2,rep,name=recommended_actions,json=recommendedActions,proto3" json:"recommended_actions,omitempty"`
}

func (x *ThreatAssessmentResponse) Reset() {
	*x = ThreatAssessmentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_equipment_ai_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ThreatAssessmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreatAssessmentResponse) ProtoMessage() {}

func (x *ThreatAssessmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_equipment_ai_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreatAssessmentResponse.ProtoReflect.Descriptor instead.
func (*ThreatAssessmentResponse) Descriptor() ([]byte, []int) {
	return file_equipment_ai_proto_rawDescGZIP(), []int{4}
}

func (x *ThreatAssessmentResponse) GetThreatLevel() string {
	if x != nil {
		return x.ThreatLevel
	}
	return ""
}

func (x *ThreatAssessmentResponse) GetRecommendedActions() []string {
	if x != nil {
		return x.RecommendedActions
	}
	return nil
}

type EquipmentData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UsageHistory     []string `protobuf:"bytes,2,rep,name=usage_history,json=usageHistory,proto3" json:"usage_history,omitempty"`
	CurrentCondition string   `protobuf:"bytes,3,opt,name=current_condition,json=currentCondition,proto3" json:"current_condition,omitempty"`
}

func (x *EquipmentData) Reset() {
	*x = EquipmentData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_equipment_ai_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EquipmentData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentData) ProtoMessage() {}

func (x *EquipmentData) ProtoReflect() protoreflect.Message {
	mi := &file_equipment_ai_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentData.ProtoReflect.Descriptor instead.
func (*EquipmentData) Descriptor() ([]byte, []int) {
	return file_equipment_ai_proto_rawDescGZIP(), []int{5}
}

func (x *EquipmentData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EquipmentData) GetUsageHistory() []string {
	if x != nil {
		return x.UsageHistory
	}
	return nil
}

func (x *EquipmentData) GetCurrentCondition() string {
	if x != nil {
		return x.CurrentCondition
	}
	return ""
}

type EquipmentMaintenanceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaintenanceSchedule []string `protobuf:"bytes,1,rep,name=maintenance_schedule,json=maintenanceSchedule,proto3" json:"maintenance_schedule,omitempty"`
	PredictedFailures   []string `protobuf:"bytes,2,rep,name=predicted_failures,json=predictedFailures,proto3" json:"predicted_failures,omitempty"`
}

func (x *EquipmentMaintenanceResponse) Reset() {
	*x = EquipmentMaintenanceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_equipment_ai_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EquipmentMaintenanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentMaintenanceResponse) ProtoMessage() {}

func (x *EquipmentMaintenanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_equipment_ai_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentMaintenanceResponse.ProtoReflect.Descriptor instead.
func (*EquipmentMaintenanceResponse) Descriptor() ([]byte, []int) {
	return file_equipment_ai_proto_rawDescGZIP(), []int{6}
}

func (x *EquipmentMaintenanceResponse) GetMaintenanceSchedule() []string {
	if x != nil {
		return x.MaintenanceSchedule
	}
	return nil
}

func (x *EquipmentMaintenanceResponse) GetPredictedFailures() []string {
	if x != nil {
		return x.PredictedFailures
	}
	return nil
}

var File_equipment_ai_proto protoreflect.FileDescriptor

var file_equipment_ai_proto_rawDesc = []byte{
	0x0a, 0x12, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x61, 0x69, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9d, 0x01, 0x0a, 0x0b, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65,
	0x6e, 0x74, 0x41, 0x49, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x6d,
	0x6d, 0x6f, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61,
	0x6d, 0x6d, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x12, 0x3b, 0x0a, 0x0e, 0x75, 0x73, 0x61, 0x67, 0x65,
	0x5f, 0x74, 0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x55, 0x73, 0x61, 0x67, 0x65, 0x54, 0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x53,
	0x74, 0x65, 0x70, 0x41, 0x49, 0x52, 0x0d, 0x75, 0x73, 0x61, 0x67, 0x65, 0x54, 0x75, 0x74, 0x6f,
	0x72, 0x69, 0x61, 0x6c, 0x22, 0x4a, 0x0a, 0x13, 0x55, 0x73, 0x61, 0x67, 0x65, 0x54, 0x75, 0x74,
	0x6f, 0x72, 0x69, 0x61, 0x6c, 0x53, 0x74, 0x65, 0x70, 0x41, 0x49, 0x12, 0x1f, 0x0a, 0x0b, 0x73,
	0x74, 0x65, 0x70, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x73, 0x74, 0x65, 0x70, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x74, 0x65, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x74, 0x65, 0x70,
	0x22, 0x2c, 0x0a, 0x12, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x41, 0x49, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x22, 0x56,
	0x0a, 0x0a, 0x54, 0x68, 0x72, 0x65, 0x61, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x6e, 0x0a, 0x18, 0x54, 0x68, 0x72, 0x65, 0x61, 0x74,
	0x41, 0x73, 0x73, 0x65, 0x73, 0x73, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x68, 0x72, 0x65, 0x61, 0x74, 0x5f, 0x6c, 0x65, 0x76,
	0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x68, 0x72, 0x65, 0x61, 0x74,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x2f, 0x0a, 0x13, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x64, 0x65, 0x64, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x12, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x71, 0x0a, 0x0d, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d,
	0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x75, 0x73, 0x61, 0x67, 0x65,
	0x5f, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c,
	0x75, 0x73, 0x61, 0x67, 0x65, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x2b, 0x0a, 0x11,
	0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x80, 0x01, 0x0a, 0x1c, 0x45, 0x71,
	0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x61, 0x6e,
	0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x14, 0x6d, 0x61,
	0x69, 0x6e, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x13, 0x6d, 0x61, 0x69, 0x6e, 0x74, 0x65,
	0x6e, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x2d, 0x0a,
	0x12, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x66, 0x61, 0x69, 0x6c, 0x75,
	0x72, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x11, 0x70, 0x72, 0x65, 0x64, 0x69,
	0x63, 0x74, 0x65, 0x64, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x73, 0x32, 0xc8, 0x01, 0x0a,
	0x09, 0x41, 0x49, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x35, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x13,
	0x2e, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x41, 0x49, 0x1a, 0x0c, 0x2e, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x41,
	0x49, 0x12, 0x36, 0x0a, 0x0c, 0x41, 0x73, 0x73, 0x65, 0x73, 0x73, 0x54, 0x68, 0x72, 0x65, 0x61,
	0x74, 0x12, 0x0b, 0x2e, 0x54, 0x68, 0x72, 0x65, 0x61, 0x74, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x19,
	0x2e, 0x54, 0x68, 0x72, 0x65, 0x61, 0x74, 0x41, 0x73, 0x73, 0x65, 0x73, 0x73, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c, 0x0a, 0x1b, 0x50, 0x72, 0x65,
	0x64, 0x69, 0x63, 0x74, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x69,
	0x6e, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x0e, 0x2e, 0x45, 0x71, 0x75, 0x69, 0x70,
	0x6d, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x1d, 0x2e, 0x45, 0x71, 0x75, 0x69, 0x70,
	0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x67, 0x65, 0x6e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_equipment_ai_proto_rawDescOnce sync.Once
	file_equipment_ai_proto_rawDescData = file_equipment_ai_proto_rawDesc
)

func file_equipment_ai_proto_rawDescGZIP() []byte {
	file_equipment_ai_proto_rawDescOnce.Do(func() {
		file_equipment_ai_proto_rawDescData = protoimpl.X.CompressGZIP(file_equipment_ai_proto_rawDescData)
	})
	return file_equipment_ai_proto_rawDescData
}

var file_equipment_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_equipment_ai_proto_goTypes = []any{
	(*EquipmentAI)(nil),                  // 0: EquipmentAI
	(*UsageTutorialStepAI)(nil),          // 1: UsageTutorialStepAI
	(*EquipmentRequestAI)(nil),           // 2: EquipmentRequestAI
	(*ThreatData)(nil),                   // 3: ThreatData
	(*ThreatAssessmentResponse)(nil),     // 4: ThreatAssessmentResponse
	(*EquipmentData)(nil),                // 5: EquipmentData
	(*EquipmentMaintenanceResponse)(nil), // 6: EquipmentMaintenanceResponse
}
var file_equipment_ai_proto_depIdxs = []int32{
	1, // 0: EquipmentAI.usage_tutorial:type_name -> UsageTutorialStepAI
	2, // 1: AIService.GetEquipmentInfo:input_type -> EquipmentRequestAI
	3, // 2: AIService.AssessThreat:input_type -> ThreatData
	5, // 3: AIService.PredictEquipmentMaintenance:input_type -> EquipmentData
	0, // 4: AIService.GetEquipmentInfo:output_type -> EquipmentAI
	4, // 5: AIService.AssessThreat:output_type -> ThreatAssessmentResponse
	6, // 6: AIService.PredictEquipmentMaintenance:output_type -> EquipmentMaintenanceResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_equipment_ai_proto_init() }
func file_equipment_ai_proto_init() {
	if File_equipment_ai_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_equipment_ai_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*EquipmentAI); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_equipment_ai_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*UsageTutorialStepAI); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_equipment_ai_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*EquipmentRequestAI); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_equipment_ai_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ThreatData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_equipment_ai_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ThreatAssessmentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_equipment_ai_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*EquipmentData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_equipment_ai_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*EquipmentMaintenanceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_equipment_ai_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_equipment_ai_proto_goTypes,
		DependencyIndexes: file_equipment_ai_proto_depIdxs,
		MessageInfos:      file_equipment_ai_proto_msgTypes,
	}.Build()
	File_equipment_ai_proto = out.File
	file_equipment_ai_proto_rawDesc = nil
	file_equipment_ai_proto_goTypes = nil
	file_equipment_ai_proto_depIdxs = nil
}
