// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.12.4
// source: equipment_ai.proto

package genprotos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	AIService_GetEquipmentInfo_FullMethodName = "/AIService/GetEquipmentInfo"
	AIService_AssessThreat_FullMethodName     = "/AIService/AssessThreat"
)

// AIServiceClient is the client API for AIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIServiceClient interface {
	GetEquipmentInfo(ctx context.Context, in *EquipmentRequestAI, opts ...grpc.CallOption) (*EquipmentAI, error)
	AssessThreat(ctx context.Context, in *ThreatData, opts ...grpc.CallOption) (*ThreatAssessmentResponse, error)
}

type aIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIServiceClient(cc grpc.ClientConnInterface) AIServiceClient {
	return &aIServiceClient{cc}
}

func (c *aIServiceClient) GetEquipmentInfo(ctx context.Context, in *EquipmentRequestAI, opts ...grpc.CallOption) (*EquipmentAI, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EquipmentAI)
	err := c.cc.Invoke(ctx, AIService_GetEquipmentInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) AssessThreat(ctx context.Context, in *ThreatData, opts ...grpc.CallOption) (*ThreatAssessmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ThreatAssessmentResponse)
	err := c.cc.Invoke(ctx, AIService_AssessThreat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIServiceServer is the server API for AIService service.
// All implementations must embed UnimplementedAIServiceServer
// for forward compatibility
type AIServiceServer interface {
	GetEquipmentInfo(context.Context, *EquipmentRequestAI) (*EquipmentAI, error)
	AssessThreat(context.Context, *ThreatData) (*ThreatAssessmentResponse, error)
	mustEmbedUnimplementedAIServiceServer()
}

// UnimplementedAIServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAIServiceServer struct {
}

func (UnimplementedAIServiceServer) GetEquipmentInfo(context.Context, *EquipmentRequestAI) (*EquipmentAI, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEquipmentInfo not implemented")
}
func (UnimplementedAIServiceServer) AssessThreat(context.Context, *ThreatData) (*ThreatAssessmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssessThreat not implemented")
}
func (UnimplementedAIServiceServer) mustEmbedUnimplementedAIServiceServer() {}

// UnsafeAIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIServiceServer will
// result in compilation errors.
type UnsafeAIServiceServer interface {
	mustEmbedUnimplementedAIServiceServer()
}

func RegisterAIServiceServer(s grpc.ServiceRegistrar, srv AIServiceServer) {
	s.RegisterService(&AIService_ServiceDesc, srv)
}

func _AIService_GetEquipmentInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EquipmentRequestAI)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).GetEquipmentInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_GetEquipmentInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).GetEquipmentInfo(ctx, req.(*EquipmentRequestAI))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_AssessThreat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ThreatData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).AssessThreat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_AssessThreat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).AssessThreat(ctx, req.(*ThreatData))
	}
	return interceptor(ctx, in, info, handler)
}

// AIService_ServiceDesc is the grpc.ServiceDesc for AIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AIService",
	HandlerType: (*AIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEquipmentInfo",
			Handler:    _AIService_GetEquipmentInfo_Handler,
		},
		{
			MethodName: "AssessThreat",
			Handler:    _AIService_AssessThreat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "equipment_ai.proto",
}
