generate-rpc:
	protoc \
	--go_out=. \
	--go-grpc_out=. \
	# protos/ai_protos/ai_protos.proto \
	# protos/ammos_protos/ammos.proto \
	# protos/equipments_protos/equipments.proto \
	# protos/fuels_protos/fuel.proto \
	# protos/soldiers_protos/soldiers.proto


