// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: protos/ammos_protos/ammos.proto

package genprotos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ammo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Caliber     string `protobuf:"bytes,3,opt,name=caliber,proto3" json:"caliber,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Type        string `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Quantity    int64  `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	LastUpdate  string `protobuf:"bytes,7,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
}

func (x *Ammo) Reset() {
	*x = Ammo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_ammos_protos_ammos_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ammo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ammo) ProtoMessage() {}

func (x *Ammo) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ammos_protos_ammos_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ammo.ProtoReflect.Descriptor instead.
func (*Ammo) Descriptor() ([]byte, []int) {
	return file_protos_ammos_protos_ammos_proto_rawDescGZIP(), []int{0}
}

func (x *Ammo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Ammo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Ammo) GetCaliber() string {
	if x != nil {
		return x.Caliber
	}
	return ""
}

func (x *Ammo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Ammo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Ammo) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Ammo) GetLastUpdate() string {
	if x != nil {
		return x.LastUpdate
	}
	return ""
}

type AmmoHistory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AmmoId          string `protobuf:"bytes,2,opt,name=ammo_id,json=ammoId,proto3" json:"ammo_id,omitempty"`
	Action          string `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	ActorId         string `protobuf:"bytes,4,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	ActionTimestamp string `protobuf:"bytes,5,opt,name=action_timestamp,json=actionTimestamp,proto3" json:"action_timestamp,omitempty"`
}

func (x *AmmoHistory) Reset() {
	*x = AmmoHistory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_ammos_protos_ammos_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AmmoHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AmmoHistory) ProtoMessage() {}

func (x *AmmoHistory) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ammos_protos_ammos_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AmmoHistory.ProtoReflect.Descriptor instead.
func (*AmmoHistory) Descriptor() ([]byte, []int) {
	return file_protos_ammos_protos_ammos_proto_rawDescGZIP(), []int{1}
}

func (x *AmmoHistory) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AmmoHistory) GetAmmoId() string {
	if x != nil {
		return x.AmmoId
	}
	return ""
}

func (x *AmmoHistory) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AmmoHistory) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *AmmoHistory) GetActionTimestamp() string {
	if x != nil {
		return x.ActionTimestamp
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_ammos_protos_ammos_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ammos_protos_ammos_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_protos_ammos_protos_ammos_proto_rawDescGZIP(), []int{2}
}

type CreateAmmoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Caliber     string `protobuf:"bytes,2,opt,name=caliber,proto3" json:"caliber,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type        string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Quantity    int64  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *CreateAmmoRequest) Reset() {
	*x = CreateAmmoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_ammos_protos_ammos_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAmmoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAmmoRequest) ProtoMessage() {}

func (x *CreateAmmoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ammos_protos_ammos_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAmmoRequest.ProtoReflect.Descriptor instead.
func (*CreateAmmoRequest) Descriptor() ([]byte, []int) {
	return file_protos_ammos_protos_ammos_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAmmoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAmmoRequest) GetCaliber() string {
	if x != nil {
		return x.Caliber
	}
	return ""
}

func (x *CreateAmmoRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateAmmoRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateAmmoRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type AmmoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ammo *Ammo `protobuf:"bytes,1,opt,name=ammo,proto3" json:"ammo,omitempty"`
}

func (x *AmmoResponse) Reset() {
	*x = AmmoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_ammos_protos_ammos_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AmmoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AmmoResponse) ProtoMessage() {}

func (x *AmmoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ammos_protos_ammos_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AmmoResponse.ProtoReflect.Descriptor instead.
func (*AmmoResponse) Descriptor() ([]byte, []int) {
	return file_protos_ammos_protos_ammos_proto_rawDescGZIP(), []int{4}
}

func (x *AmmoResponse) GetAmmo() *Ammo {
	if x != nil {
		return x.Ammo
	}
	return nil
}

type GetAmmoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ammo []*Ammo `protobuf:"bytes,1,rep,name=ammo,proto3" json:"ammo,omitempty"`
}

func (x *GetAmmoResponse) Reset() {
	*x = GetAmmoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_ammos_protos_ammos_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAmmoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAmmoResponse) ProtoMessage() {}

func (x *GetAmmoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ammos_protos_ammos_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAmmoResponse.ProtoReflect.Descriptor instead.
func (*GetAmmoResponse) Descriptor() ([]byte, []int) {
	return file_protos_ammos_protos_ammos_proto_rawDescGZIP(), []int{5}
}

func (x *GetAmmoResponse) GetAmmo() []*Ammo {
	if x != nil {
		return x.Ammo
	}
	return nil
}

type GetAmmoByChoiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Choice  string `protobuf:"bytes,1,opt,name=choice,proto3" json:"choice,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GetAmmoByChoiceRequest) Reset() {
	*x = GetAmmoByChoiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_ammos_protos_ammos_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAmmoByChoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAmmoByChoiceRequest) ProtoMessage() {}

func (x *GetAmmoByChoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ammos_protos_ammos_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAmmoByChoiceRequest.ProtoReflect.Descriptor instead.
func (*GetAmmoByChoiceRequest) Descriptor() ([]byte, []int) {
	return file_protos_ammos_protos_ammos_proto_rawDescGZIP(), []int{6}
}

func (x *GetAmmoByChoiceRequest) GetChoice() string {
	if x != nil {
		return x.Choice
	}
	return ""
}

func (x *GetAmmoByChoiceRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateAmmoByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Caliber     string `protobuf:"bytes,3,opt,name=caliber,proto3" json:"caliber,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Type        string `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Quantity    int64  `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *UpdateAmmoByIdRequest) Reset() {
	*x = UpdateAmmoByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_ammos_protos_ammos_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAmmoByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAmmoByIdRequest) ProtoMessage() {}

func (x *UpdateAmmoByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ammos_protos_ammos_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAmmoByIdRequest.ProtoReflect.Descriptor instead.
func (*UpdateAmmoByIdRequest) Descriptor() ([]byte, []int) {
	return file_protos_ammos_protos_ammos_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateAmmoByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAmmoByIdRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateAmmoByIdRequest) GetCaliber() string {
	if x != nil {
		return x.Caliber
	}
	return ""
}

func (x *UpdateAmmoByIdRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateAmmoByIdRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateAmmoByIdRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type DeleteAmmoByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteAmmoByIdRequest) Reset() {
	*x = DeleteAmmoByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_ammos_protos_ammos_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAmmoByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAmmoByIdRequest) ProtoMessage() {}

func (x *DeleteAmmoByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ammos_protos_ammos_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAmmoByIdRequest.ProtoReflect.Descriptor instead.
func (*DeleteAmmoByIdRequest) Descriptor() ([]byte, []int) {
	return file_protos_ammos_protos_ammos_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteAmmoByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateAmmoHistoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AmmoId  string `protobuf:"bytes,1,opt,name=ammo_id,json=ammoId,proto3" json:"ammo_id,omitempty"`
	Action  string `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	ActorId string `protobuf:"bytes,3,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
}

func (x *CreateAmmoHistoryRequest) Reset() {
	*x = CreateAmmoHistoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_ammos_protos_ammos_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAmmoHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAmmoHistoryRequest) ProtoMessage() {}

func (x *CreateAmmoHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ammos_protos_ammos_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAmmoHistoryRequest.ProtoReflect.Descriptor instead.
func (*CreateAmmoHistoryRequest) Descriptor() ([]byte, []int) {
	return file_protos_ammos_protos_ammos_proto_rawDescGZIP(), []int{9}
}

func (x *CreateAmmoHistoryRequest) GetAmmoId() string {
	if x != nil {
		return x.AmmoId
	}
	return ""
}

func (x *CreateAmmoHistoryRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CreateAmmoHistoryRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

type DeleteAmmoHistoryByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteAmmoHistoryByIdRequest) Reset() {
	*x = DeleteAmmoHistoryByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_ammos_protos_ammos_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAmmoHistoryByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAmmoHistoryByIdRequest) ProtoMessage() {}

func (x *DeleteAmmoHistoryByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ammos_protos_ammos_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAmmoHistoryByIdRequest.ProtoReflect.Descriptor instead.
func (*DeleteAmmoHistoryByIdRequest) Descriptor() ([]byte, []int) {
	return file_protos_ammos_protos_ammos_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteAmmoHistoryByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAmmoHistoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AmmoHistory []*AmmoHistory `protobuf:"bytes,1,rep,name=ammo_history,json=ammoHistory,proto3" json:"ammo_history,omitempty"`
}

func (x *GetAmmoHistoryResponse) Reset() {
	*x = GetAmmoHistoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_ammos_protos_ammos_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAmmoHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAmmoHistoryResponse) ProtoMessage() {}

func (x *GetAmmoHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ammos_protos_ammos_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAmmoHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetAmmoHistoryResponse) Descriptor() ([]byte, []int) {
	return file_protos_ammos_protos_ammos_proto_rawDescGZIP(), []int{11}
}

func (x *GetAmmoHistoryResponse) GetAmmoHistory() []*AmmoHistory {
	if x != nil {
		return x.AmmoHistory
	}
	return nil
}

type GetAmmoHistoryByChoiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Choice  string `protobuf:"bytes,1,opt,name=choice,proto3" json:"choice,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GetAmmoHistoryByChoiceRequest) Reset() {
	*x = GetAmmoHistoryByChoiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_ammos_protos_ammos_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAmmoHistoryByChoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAmmoHistoryByChoiceRequest) ProtoMessage() {}

func (x *GetAmmoHistoryByChoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ammos_protos_ammos_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAmmoHistoryByChoiceRequest.ProtoReflect.Descriptor instead.
func (*GetAmmoHistoryByChoiceRequest) Descriptor() ([]byte, []int) {
	return file_protos_ammos_protos_ammos_proto_rawDescGZIP(), []int{12}
}

func (x *GetAmmoHistoryByChoiceRequest) GetChoice() string {
	if x != nil {
		return x.Choice
	}
	return ""
}

func (x *GetAmmoHistoryByChoiceRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetAmmoHistoryByChoiceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AmmoHistory []*AmmoHistory `protobuf:"bytes,1,rep,name=ammo_history,json=ammoHistory,proto3" json:"ammo_history,omitempty"`
}

func (x *GetAmmoHistoryByChoiceResponse) Reset() {
	*x = GetAmmoHistoryByChoiceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_ammos_protos_ammos_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAmmoHistoryByChoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAmmoHistoryByChoiceResponse) ProtoMessage() {}

func (x *GetAmmoHistoryByChoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ammos_protos_ammos_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAmmoHistoryByChoiceResponse.ProtoReflect.Descriptor instead.
func (*GetAmmoHistoryByChoiceResponse) Descriptor() ([]byte, []int) {
	return file_protos_ammos_protos_ammos_proto_rawDescGZIP(), []int{13}
}

func (x *GetAmmoHistoryByChoiceResponse) GetAmmoHistory() []*AmmoHistory {
	if x != nil {
		return x.AmmoHistory
	}
	return nil
}

type GetAmmoByChoiceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ammo []*Ammo `protobuf:"bytes,1,rep,name=ammo,proto3" json:"ammo,omitempty"`
}

func (x *GetAmmoByChoiceResponse) Reset() {
	*x = GetAmmoByChoiceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_ammos_protos_ammos_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAmmoByChoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAmmoByChoiceResponse) ProtoMessage() {}

func (x *GetAmmoByChoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ammos_protos_ammos_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAmmoByChoiceResponse.ProtoReflect.Descriptor instead.
func (*GetAmmoByChoiceResponse) Descriptor() ([]byte, []int) {
	return file_protos_ammos_protos_ammos_proto_rawDescGZIP(), []int{14}
}

func (x *GetAmmoByChoiceResponse) GetAmmo() []*Ammo {
	if x != nil {
		return x.Ammo
	}
	return nil
}

type UpdateAmmoHistoryByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AmmoId  string `protobuf:"bytes,2,opt,name=ammo_id,json=ammoId,proto3" json:"ammo_id,omitempty"`
	Action  string `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	ActorId string `protobuf:"bytes,4,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
}

func (x *UpdateAmmoHistoryByIdRequest) Reset() {
	*x = UpdateAmmoHistoryByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_ammos_protos_ammos_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAmmoHistoryByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAmmoHistoryByIdRequest) ProtoMessage() {}

func (x *UpdateAmmoHistoryByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ammos_protos_ammos_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAmmoHistoryByIdRequest.ProtoReflect.Descriptor instead.
func (*UpdateAmmoHistoryByIdRequest) Descriptor() ([]byte, []int) {
	return file_protos_ammos_protos_ammos_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateAmmoHistoryByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAmmoHistoryByIdRequest) GetAmmoId() string {
	if x != nil {
		return x.AmmoId
	}
	return ""
}

func (x *UpdateAmmoHistoryByIdRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *UpdateAmmoHistoryByIdRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

type GetAmmoHistoryByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetAmmoHistoryByIdRequest) Reset() {
	*x = GetAmmoHistoryByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_ammos_protos_ammos_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAmmoHistoryByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAmmoHistoryByIdRequest) ProtoMessage() {}

func (x *GetAmmoHistoryByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ammos_protos_ammos_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAmmoHistoryByIdRequest.ProtoReflect.Descriptor instead.
func (*GetAmmoHistoryByIdRequest) Descriptor() ([]byte, []int) {
	return file_protos_ammos_protos_ammos_proto_rawDescGZIP(), []int{16}
}

func (x *GetAmmoHistoryByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAmmoHistoryByDateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *GetAmmoHistoryByDateRequest) Reset() {
	*x = GetAmmoHistoryByDateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_ammos_protos_ammos_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAmmoHistoryByDateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAmmoHistoryByDateRequest) ProtoMessage() {}

func (x *GetAmmoHistoryByDateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ammos_protos_ammos_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAmmoHistoryByDateRequest.ProtoReflect.Descriptor instead.
func (*GetAmmoHistoryByDateRequest) Descriptor() ([]byte, []int) {
	return file_protos_ammos_protos_ammos_proto_rawDescGZIP(), []int{17}
}

func (x *GetAmmoHistoryByDateRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type GetAmmoHistoryByDateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AmmoHistory []*AmmoHistory `protobuf:"bytes,1,rep,name=ammo_history,json=ammoHistory,proto3" json:"ammo_history,omitempty"`
}

func (x *GetAmmoHistoryByDateResponse) Reset() {
	*x = GetAmmoHistoryByDateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_ammos_protos_ammos_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAmmoHistoryByDateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAmmoHistoryByDateResponse) ProtoMessage() {}

func (x *GetAmmoHistoryByDateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ammos_protos_ammos_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAmmoHistoryByDateResponse.ProtoReflect.Descriptor instead.
func (*GetAmmoHistoryByDateResponse) Descriptor() ([]byte, []int) {
	return file_protos_ammos_protos_ammos_proto_rawDescGZIP(), []int{18}
}

func (x *GetAmmoHistoryByDateResponse) GetAmmoHistory() []*AmmoHistory {
	if x != nil {
		return x.AmmoHistory
	}
	return nil
}

var File_protos_ammos_protos_ammos_proto protoreflect.FileDescriptor

var file_protos_ammos_protos_ammos_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x61, 0x6d, 0x6d, 0x6f, 0x73, 0x5f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x61, 0x6d, 0x6d, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xb7, 0x01, 0x0a, 0x04, 0x41, 0x6d, 0x6d, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x61, 0x6c, 0x69, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x61, 0x6c, 0x69, 0x62, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x61,
	0x73, 0x74, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x22, 0x94, 0x01, 0x0a, 0x0b,
	0x41, 0x6d, 0x6d, 0x6f, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x61,
	0x6d, 0x6d, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d,
	0x6d, 0x6f, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08,
	0x61, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x10, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x93, 0x01, 0x0a, 0x11,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x6d, 0x6d, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x61, 0x6c, 0x69, 0x62, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x61, 0x6c, 0x69, 0x62, 0x65, 0x72, 0x12,
	0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x22, 0x29, 0x0a, 0x0c, 0x41, 0x6d, 0x6d, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x19, 0x0a, 0x04, 0x61, 0x6d, 0x6d, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x05, 0x2e, 0x41, 0x6d, 0x6d, 0x6f, 0x52, 0x04, 0x61, 0x6d, 0x6d, 0x6f, 0x22, 0x2c, 0x0a, 0x0f,
	0x47, 0x65, 0x74, 0x41, 0x6d, 0x6d, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x19, 0x0a, 0x04, 0x61, 0x6d, 0x6d, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e,
	0x41, 0x6d, 0x6d, 0x6f, 0x52, 0x04, 0x61, 0x6d, 0x6d, 0x6f, 0x22, 0x4a, 0x0a, 0x16, 0x47, 0x65,
	0x74, 0x41, 0x6d, 0x6d, 0x6f, 0x42, 0x79, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xa7, 0x01, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x41, 0x6d, 0x6d, 0x6f, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x61, 0x6c, 0x69, 0x62, 0x65, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x61, 0x6c, 0x69, 0x62, 0x65, 0x72, 0x12, 0x20,
	0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x22, 0x27, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x6d, 0x6d, 0x6f, 0x42, 0x79,
	0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x66, 0x0a, 0x18, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x41, 0x6d, 0x6d, 0x6f, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x6d, 0x6d, 0x6f, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6d, 0x6f, 0x49, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x49,
	0x64, 0x22, 0x2e, 0x0a, 0x1c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x6d, 0x6d, 0x6f, 0x48,
	0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x49, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x41, 0x6d, 0x6d, 0x6f, 0x48, 0x69, 0x73, 0x74,
	0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x0c, 0x61,
	0x6d, 0x6d, 0x6f, 0x5f, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x41, 0x6d, 0x6d, 0x6f, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52,
	0x0b, 0x61, 0x6d, 0x6d, 0x6f, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x22, 0x51, 0x0a, 0x1d,
	0x47, 0x65, 0x74, 0x41, 0x6d, 0x6d, 0x6f, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x42, 0x79,
	0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x63, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63,
	0x68, 0x6f, 0x69, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x51, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x41, 0x6d, 0x6d, 0x6f, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72,
	0x79, 0x42, 0x79, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2f, 0x0a, 0x0c, 0x61, 0x6d, 0x6d, 0x6f, 0x5f, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72,
	0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x41, 0x6d, 0x6d, 0x6f, 0x48, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x0b, 0x61, 0x6d, 0x6d, 0x6f, 0x48, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x22, 0x34, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x41, 0x6d, 0x6d, 0x6f, 0x42, 0x79, 0x43,
	0x68, 0x6f, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a,
	0x04, 0x61, 0x6d, 0x6d, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x41, 0x6d,
	0x6d, 0x6f, 0x52, 0x04, 0x61, 0x6d, 0x6d, 0x6f, 0x22, 0x7a, 0x0a, 0x1c, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x41, 0x6d, 0x6d, 0x6f, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x42, 0x79, 0x49,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x6d, 0x6d, 0x6f,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6d, 0x6f, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x63, 0x74,
	0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x74,
	0x6f, 0x72, 0x49, 0x64, 0x22, 0x2b, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x41, 0x6d, 0x6d, 0x6f, 0x48,
	0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x31, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x41, 0x6d, 0x6d, 0x6f, 0x48, 0x69, 0x73, 0x74,
	0x6f, 0x72, 0x79, 0x42, 0x79, 0x44, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x65, 0x22, 0x4f, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x41, 0x6d, 0x6d, 0x6f, 0x48,
	0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x42, 0x79, 0x44, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x0c, 0x61, 0x6d, 0x6d, 0x6f, 0x5f, 0x68, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x41, 0x6d, 0x6d,
	0x6f, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x0b, 0x61, 0x6d, 0x6d, 0x6f, 0x48, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x32, 0xfc, 0x05, 0x0a, 0x0c, 0x41, 0x6d, 0x6d, 0x6f, 0x73, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2f, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x41, 0x6d, 0x6d, 0x6f, 0x12, 0x12, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x6d, 0x6d,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x41, 0x6d, 0x6d, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x41, 0x6d,
	0x6d, 0x6f, 0x42, 0x79, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x12, 0x17, 0x2e, 0x47, 0x65, 0x74,
	0x41, 0x6d, 0x6d, 0x6f, 0x42, 0x79, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6d, 0x6d, 0x6f, 0x42, 0x79, 0x43,
	0x68, 0x6f, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a,
	0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x6d, 0x6d, 0x6f, 0x42, 0x79, 0x49, 0x64, 0x12,
	0x16, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x6d, 0x6d, 0x6f, 0x42, 0x79, 0x49, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x41, 0x6d, 0x6d, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x41, 0x6d, 0x6d, 0x6f, 0x42, 0x79, 0x49, 0x64, 0x12, 0x16, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x41, 0x6d, 0x6d, 0x6f, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x23, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x41,
	0x6d, 0x6d, 0x6f, 0x12, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x10, 0x2e, 0x47, 0x65,
	0x74, 0x41, 0x6d, 0x6d, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a,
	0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x6d, 0x6d, 0x6f, 0x48, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x12, 0x19, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x6d, 0x6d, 0x6f, 0x48,
	0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e,
	0x41, 0x6d, 0x6d, 0x6f, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x59, 0x0a, 0x16, 0x47,
	0x65, 0x74, 0x41, 0x6d, 0x6d, 0x6f, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x42, 0x79, 0x43,
	0x68, 0x6f, 0x69, 0x63, 0x65, 0x12, 0x1e, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6d, 0x6d, 0x6f, 0x48,
	0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x42, 0x79, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6d, 0x6d, 0x6f, 0x48,
	0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x42, 0x79, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x41, 0x6d, 0x6d,
	0x6f, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x42, 0x79, 0x49, 0x64, 0x12, 0x1a, 0x2e, 0x47,
	0x65, 0x74, 0x41, 0x6d, 0x6d, 0x6f, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x42, 0x79, 0x49,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x41, 0x6d, 0x6d, 0x6f, 0x48,
	0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x53, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x41, 0x6d, 0x6d,
	0x6f, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x42, 0x79, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1c,
	0x2e, 0x47, 0x65, 0x74, 0x41, 0x6d, 0x6d, 0x6f, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x42,
	0x79, 0x44, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x47,
	0x65, 0x74, 0x41, 0x6d, 0x6d, 0x6f, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x42, 0x79, 0x44,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x15, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x6d, 0x6d, 0x6f, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79,
	0x42, 0x79, 0x49, 0x64, 0x12, 0x1d, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x6d, 0x6d,
	0x6f, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x41, 0x6d, 0x6d, 0x6f, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72,
	0x79, 0x12, 0x3e, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x6d, 0x6d, 0x6f, 0x48,
	0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x42, 0x79, 0x49, 0x64, 0x12, 0x1d, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x41, 0x6d, 0x6d, 0x6f, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x42, 0x79,
	0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x12, 0x31, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x41, 0x6d, 0x6d, 0x6f, 0x48, 0x69, 0x73, 0x74,
	0x6f, 0x72, 0x79, 0x12, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x17, 0x2e, 0x47, 0x65,
	0x74, 0x41, 0x6d, 0x6d, 0x6f, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_ammos_protos_ammos_proto_rawDescOnce sync.Once
	file_protos_ammos_protos_ammos_proto_rawDescData = file_protos_ammos_protos_ammos_proto_rawDesc
)

func file_protos_ammos_protos_ammos_proto_rawDescGZIP() []byte {
	file_protos_ammos_protos_ammos_proto_rawDescOnce.Do(func() {
		file_protos_ammos_protos_ammos_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_ammos_protos_ammos_proto_rawDescData)
	})
	return file_protos_ammos_protos_ammos_proto_rawDescData
}

var file_protos_ammos_protos_ammos_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_protos_ammos_protos_ammos_proto_goTypes = []any{
	(*Ammo)(nil),                           // 0: Ammo
	(*AmmoHistory)(nil),                    // 1: AmmoHistory
	(*Empty)(nil),                          // 2: Empty
	(*CreateAmmoRequest)(nil),              // 3: CreateAmmoRequest
	(*AmmoResponse)(nil),                   // 4: AmmoResponse
	(*GetAmmoResponse)(nil),                // 5: GetAmmoResponse
	(*GetAmmoByChoiceRequest)(nil),         // 6: GetAmmoByChoiceRequest
	(*UpdateAmmoByIdRequest)(nil),          // 7: UpdateAmmoByIdRequest
	(*DeleteAmmoByIdRequest)(nil),          // 8: DeleteAmmoByIdRequest
	(*CreateAmmoHistoryRequest)(nil),       // 9: CreateAmmoHistoryRequest
	(*DeleteAmmoHistoryByIdRequest)(nil),   // 10: DeleteAmmoHistoryByIdRequest
	(*GetAmmoHistoryResponse)(nil),         // 11: GetAmmoHistoryResponse
	(*GetAmmoHistoryByChoiceRequest)(nil),  // 12: GetAmmoHistoryByChoiceRequest
	(*GetAmmoHistoryByChoiceResponse)(nil), // 13: GetAmmoHistoryByChoiceResponse
	(*GetAmmoByChoiceResponse)(nil),        // 14: GetAmmoByChoiceResponse
	(*UpdateAmmoHistoryByIdRequest)(nil),   // 15: UpdateAmmoHistoryByIdRequest
	(*GetAmmoHistoryByIdRequest)(nil),      // 16: GetAmmoHistoryByIdRequest
	(*GetAmmoHistoryByDateRequest)(nil),    // 17: GetAmmoHistoryByDateRequest
	(*GetAmmoHistoryByDateResponse)(nil),   // 18: GetAmmoHistoryByDateResponse
}
var file_protos_ammos_protos_ammos_proto_depIdxs = []int32{
	0,  // 0: AmmoResponse.ammo:type_name -> Ammo
	0,  // 1: GetAmmoResponse.ammo:type_name -> Ammo
	1,  // 2: GetAmmoHistoryResponse.ammo_history:type_name -> AmmoHistory
	1,  // 3: GetAmmoHistoryByChoiceResponse.ammo_history:type_name -> AmmoHistory
	0,  // 4: GetAmmoByChoiceResponse.ammo:type_name -> Ammo
	1,  // 5: GetAmmoHistoryByDateResponse.ammo_history:type_name -> AmmoHistory
	3,  // 6: AmmosService.CreateAmmo:input_type -> CreateAmmoRequest
	6,  // 7: AmmosService.GetAmmoByChoice:input_type -> GetAmmoByChoiceRequest
	7,  // 8: AmmosService.UpdateAmmoById:input_type -> UpdateAmmoByIdRequest
	8,  // 9: AmmosService.DeleteAmmoById:input_type -> DeleteAmmoByIdRequest
	2,  // 10: AmmosService.GetAmmo:input_type -> Empty
	9,  // 11: AmmosService.CreateAmmoHistory:input_type -> CreateAmmoHistoryRequest
	12, // 12: AmmosService.GetAmmoHistoryByChoice:input_type -> GetAmmoHistoryByChoiceRequest
	16, // 13: AmmosService.GetAmmoHistoryById:input_type -> GetAmmoHistoryByIdRequest
	17, // 14: AmmosService.GetAmmoHistoryByDate:input_type -> GetAmmoHistoryByDateRequest
	15, // 15: AmmosService.UpdateAmmoHistoryById:input_type -> UpdateAmmoHistoryByIdRequest
	10, // 16: AmmosService.DeleteAmmoHistoryById:input_type -> DeleteAmmoHistoryByIdRequest
	2,  // 17: AmmosService.GetAmmoHistory:input_type -> Empty
	4,  // 18: AmmosService.CreateAmmo:output_type -> AmmoResponse
	14, // 19: AmmosService.GetAmmoByChoice:output_type -> GetAmmoByChoiceResponse
	4,  // 20: AmmosService.UpdateAmmoById:output_type -> AmmoResponse
	2,  // 21: AmmosService.DeleteAmmoById:output_type -> Empty
	5,  // 22: AmmosService.GetAmmo:output_type -> GetAmmoResponse
	1,  // 23: AmmosService.CreateAmmoHistory:output_type -> AmmoHistory
	13, // 24: AmmosService.GetAmmoHistoryByChoice:output_type -> GetAmmoHistoryByChoiceResponse
	1,  // 25: AmmosService.GetAmmoHistoryById:output_type -> AmmoHistory
	18, // 26: AmmosService.GetAmmoHistoryByDate:output_type -> GetAmmoHistoryByDateResponse
	1,  // 27: AmmosService.UpdateAmmoHistoryById:output_type -> AmmoHistory
	2,  // 28: AmmosService.DeleteAmmoHistoryById:output_type -> Empty
	11, // 29: AmmosService.GetAmmoHistory:output_type -> GetAmmoHistoryResponse
	18, // [18:30] is the sub-list for method output_type
	6,  // [6:18] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_protos_ammos_protos_ammos_proto_init() }
func file_protos_ammos_protos_ammos_proto_init() {
	if File_protos_ammos_protos_ammos_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_ammos_protos_ammos_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Ammo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_ammos_protos_ammos_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AmmoHistory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_ammos_protos_ammos_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_ammos_protos_ammos_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CreateAmmoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_ammos_protos_ammos_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*AmmoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_ammos_protos_ammos_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetAmmoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_ammos_protos_ammos_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetAmmoByChoiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_ammos_protos_ammos_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateAmmoByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_ammos_protos_ammos_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteAmmoByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_ammos_protos_ammos_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*CreateAmmoHistoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_ammos_protos_ammos_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteAmmoHistoryByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_ammos_protos_ammos_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*GetAmmoHistoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_ammos_protos_ammos_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*GetAmmoHistoryByChoiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_ammos_protos_ammos_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*GetAmmoHistoryByChoiceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_ammos_protos_ammos_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*GetAmmoByChoiceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_ammos_protos_ammos_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateAmmoHistoryByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_ammos_protos_ammos_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*GetAmmoHistoryByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_ammos_protos_ammos_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*GetAmmoHistoryByDateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_ammos_protos_ammos_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*GetAmmoHistoryByDateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_ammos_protos_ammos_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_ammos_protos_ammos_proto_goTypes,
		DependencyIndexes: file_protos_ammos_protos_ammos_proto_depIdxs,
		MessageInfos:      file_protos_ammos_protos_ammos_proto_msgTypes,
	}.Build()
	File_protos_ammos_protos_ammos_proto = out.File
	file_protos_ammos_protos_ammos_proto_rawDesc = nil
	file_protos_ammos_protos_ammos_proto_goTypes = nil
	file_protos_ammos_protos_ammos_proto_depIdxs = nil
}
