// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: protos/fuels_protos/fuel.proto

package genprotos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Fuel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type       string  `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Quantity   float64 `protobuf:"fixed64,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	LastUpdate string  `protobuf:"bytes,5,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
}

func (x *Fuel) Reset() {
	*x = Fuel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_fuels_protos_fuel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fuel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fuel) ProtoMessage() {}

func (x *Fuel) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fuels_protos_fuel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fuel.ProtoReflect.Descriptor instead.
func (*Fuel) Descriptor() ([]byte, []int) {
	return file_protos_fuels_protos_fuel_proto_rawDescGZIP(), []int{0}
}

func (x *Fuel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Fuel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Fuel) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Fuel) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Fuel) GetLastUpdate() string {
	if x != nil {
		return x.LastUpdate
	}
	return ""
}

type FuelHistory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FuelId          string `protobuf:"bytes,2,opt,name=fuel_id,json=fuelId,proto3" json:"fuel_id,omitempty"`
	Action          string `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	ActiorId        string `protobuf:"bytes,4,opt,name=actior_id,json=actiorId,proto3" json:"actior_id,omitempty"`
	ActionTimestamp string `protobuf:"bytes,5,opt,name=action_timestamp,json=actionTimestamp,proto3" json:"action_timestamp,omitempty"`
}

func (x *FuelHistory) Reset() {
	*x = FuelHistory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_fuels_protos_fuel_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FuelHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuelHistory) ProtoMessage() {}

func (x *FuelHistory) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fuels_protos_fuel_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuelHistory.ProtoReflect.Descriptor instead.
func (*FuelHistory) Descriptor() ([]byte, []int) {
	return file_protos_fuels_protos_fuel_proto_rawDescGZIP(), []int{1}
}

func (x *FuelHistory) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FuelHistory) GetFuelId() string {
	if x != nil {
		return x.FuelId
	}
	return ""
}

func (x *FuelHistory) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *FuelHistory) GetActiorId() string {
	if x != nil {
		return x.ActiorId
	}
	return ""
}

func (x *FuelHistory) GetActionTimestamp() string {
	if x != nil {
		return x.ActionTimestamp
	}
	return ""
}

type CreateFuelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type     string  `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Quantity float64 `protobuf:"fixed64,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *CreateFuelRequest) Reset() {
	*x = CreateFuelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_fuels_protos_fuel_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFuelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFuelRequest) ProtoMessage() {}

func (x *CreateFuelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fuels_protos_fuel_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFuelRequest.ProtoReflect.Descriptor instead.
func (*CreateFuelRequest) Descriptor() ([]byte, []int) {
	return file_protos_fuels_protos_fuel_proto_rawDescGZIP(), []int{2}
}

func (x *CreateFuelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateFuelRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateFuelRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type GetFuelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetFuelRequest) Reset() {
	*x = GetFuelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_fuels_protos_fuel_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFuelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFuelRequest) ProtoMessage() {}

func (x *GetFuelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fuels_protos_fuel_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFuelRequest.ProtoReflect.Descriptor instead.
func (*GetFuelRequest) Descriptor() ([]byte, []int) {
	return file_protos_fuels_protos_fuel_proto_rawDescGZIP(), []int{3}
}

func (x *GetFuelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateFuelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type     string  `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Quantity float64 `protobuf:"fixed64,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *UpdateFuelRequest) Reset() {
	*x = UpdateFuelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_fuels_protos_fuel_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFuelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFuelRequest) ProtoMessage() {}

func (x *UpdateFuelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fuels_protos_fuel_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFuelRequest.ProtoReflect.Descriptor instead.
func (*UpdateFuelRequest) Descriptor() ([]byte, []int) {
	return file_protos_fuels_protos_fuel_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateFuelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateFuelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateFuelRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateFuelRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type DeleteFuelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteFuelRequest) Reset() {
	*x = DeleteFuelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_fuels_protos_fuel_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFuelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFuelRequest) ProtoMessage() {}

func (x *DeleteFuelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fuels_protos_fuel_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFuelRequest.ProtoReflect.Descriptor instead.
func (*DeleteFuelRequest) Descriptor() ([]byte, []int) {
	return file_protos_fuels_protos_fuel_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteFuelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetFuelsByChoiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Choice  string `protobuf:"bytes,1,opt,name=choice,proto3" json:"choice,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GetFuelsByChoiceRequest) Reset() {
	*x = GetFuelsByChoiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_fuels_protos_fuel_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFuelsByChoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFuelsByChoiceRequest) ProtoMessage() {}

func (x *GetFuelsByChoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fuels_protos_fuel_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFuelsByChoiceRequest.ProtoReflect.Descriptor instead.
func (*GetFuelsByChoiceRequest) Descriptor() ([]byte, []int) {
	return file_protos_fuels_protos_fuel_proto_rawDescGZIP(), []int{6}
}

func (x *GetFuelsByChoiceRequest) GetChoice() string {
	if x != nil {
		return x.Choice
	}
	return ""
}

func (x *GetFuelsByChoiceRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetFuelsByChoiceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fuels []*Fuel `protobuf:"bytes,1,rep,name=fuels,proto3" json:"fuels,omitempty"`
}

func (x *GetFuelsByChoiceResponse) Reset() {
	*x = GetFuelsByChoiceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_fuels_protos_fuel_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFuelsByChoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFuelsByChoiceResponse) ProtoMessage() {}

func (x *GetFuelsByChoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fuels_protos_fuel_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFuelsByChoiceResponse.ProtoReflect.Descriptor instead.
func (*GetFuelsByChoiceResponse) Descriptor() ([]byte, []int) {
	return file_protos_fuels_protos_fuel_proto_rawDescGZIP(), []int{7}
}

func (x *GetFuelsByChoiceResponse) GetFuels() []*Fuel {
	if x != nil {
		return x.Fuels
	}
	return nil
}

type GetFuelsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fuels []*Fuel `protobuf:"bytes,1,rep,name=fuels,proto3" json:"fuels,omitempty"`
}

func (x *GetFuelsResponse) Reset() {
	*x = GetFuelsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_fuels_protos_fuel_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFuelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFuelsResponse) ProtoMessage() {}

func (x *GetFuelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fuels_protos_fuel_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFuelsResponse.ProtoReflect.Descriptor instead.
func (*GetFuelsResponse) Descriptor() ([]byte, []int) {
	return file_protos_fuels_protos_fuel_proto_rawDescGZIP(), []int{8}
}

func (x *GetFuelsResponse) GetFuels() []*Fuel {
	if x != nil {
		return x.Fuels
	}
	return nil
}

type FuelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fuel *Fuel `protobuf:"bytes,1,opt,name=fuel,proto3" json:"fuel,omitempty"`
}

func (x *FuelResponse) Reset() {
	*x = FuelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_fuels_protos_fuel_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FuelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuelResponse) ProtoMessage() {}

func (x *FuelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fuels_protos_fuel_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuelResponse.ProtoReflect.Descriptor instead.
func (*FuelResponse) Descriptor() ([]byte, []int) {
	return file_protos_fuels_protos_fuel_proto_rawDescGZIP(), []int{9}
}

func (x *FuelResponse) GetFuel() *Fuel {
	if x != nil {
		return x.Fuel
	}
	return nil
}

type CreateFuelHistoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FuelId   string `protobuf:"bytes,1,opt,name=fuel_id,json=fuelId,proto3" json:"fuel_id,omitempty"`
	Action   string `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	ActiorId string `protobuf:"bytes,3,opt,name=actior_id,json=actiorId,proto3" json:"actior_id,omitempty"`
}

func (x *CreateFuelHistoryRequest) Reset() {
	*x = CreateFuelHistoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_fuels_protos_fuel_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFuelHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFuelHistoryRequest) ProtoMessage() {}

func (x *CreateFuelHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fuels_protos_fuel_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFuelHistoryRequest.ProtoReflect.Descriptor instead.
func (*CreateFuelHistoryRequest) Descriptor() ([]byte, []int) {
	return file_protos_fuels_protos_fuel_proto_rawDescGZIP(), []int{10}
}

func (x *CreateFuelHistoryRequest) GetFuelId() string {
	if x != nil {
		return x.FuelId
	}
	return ""
}

func (x *CreateFuelHistoryRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CreateFuelHistoryRequest) GetActiorId() string {
	if x != nil {
		return x.ActiorId
	}
	return ""
}

type GetFuelHistoriesByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetFuelHistoriesByIdRequest) Reset() {
	*x = GetFuelHistoriesByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_fuels_protos_fuel_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFuelHistoriesByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFuelHistoriesByIdRequest) ProtoMessage() {}

func (x *GetFuelHistoriesByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fuels_protos_fuel_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFuelHistoriesByIdRequest.ProtoReflect.Descriptor instead.
func (*GetFuelHistoriesByIdRequest) Descriptor() ([]byte, []int) {
	return file_protos_fuels_protos_fuel_proto_rawDescGZIP(), []int{11}
}

func (x *GetFuelHistoriesByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetFuelHistoriesByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FuelHistories []*FuelHistory `protobuf:"bytes,1,rep,name=fuel_histories,json=fuelHistories,proto3" json:"fuel_histories,omitempty"`
}

func (x *GetFuelHistoriesByIdResponse) Reset() {
	*x = GetFuelHistoriesByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_fuels_protos_fuel_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFuelHistoriesByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFuelHistoriesByIdResponse) ProtoMessage() {}

func (x *GetFuelHistoriesByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fuels_protos_fuel_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFuelHistoriesByIdResponse.ProtoReflect.Descriptor instead.
func (*GetFuelHistoriesByIdResponse) Descriptor() ([]byte, []int) {
	return file_protos_fuels_protos_fuel_proto_rawDescGZIP(), []int{12}
}

func (x *GetFuelHistoriesByIdResponse) GetFuelHistories() []*FuelHistory {
	if x != nil {
		return x.FuelHistories
	}
	return nil
}

type GetFuelHistoriesByChoiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Choice  string `protobuf:"bytes,1,opt,name=choice,proto3" json:"choice,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GetFuelHistoriesByChoiceRequest) Reset() {
	*x = GetFuelHistoriesByChoiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_fuels_protos_fuel_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFuelHistoriesByChoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFuelHistoriesByChoiceRequest) ProtoMessage() {}

func (x *GetFuelHistoriesByChoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fuels_protos_fuel_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFuelHistoriesByChoiceRequest.ProtoReflect.Descriptor instead.
func (*GetFuelHistoriesByChoiceRequest) Descriptor() ([]byte, []int) {
	return file_protos_fuels_protos_fuel_proto_rawDescGZIP(), []int{13}
}

func (x *GetFuelHistoriesByChoiceRequest) GetChoice() string {
	if x != nil {
		return x.Choice
	}
	return ""
}

func (x *GetFuelHistoriesByChoiceRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetFuelHistoriesByChoiceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FuelHistories []*FuelHistory `protobuf:"bytes,1,rep,name=fuel_histories,json=fuelHistories,proto3" json:"fuel_histories,omitempty"`
}

func (x *GetFuelHistoriesByChoiceResponse) Reset() {
	*x = GetFuelHistoriesByChoiceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_fuels_protos_fuel_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFuelHistoriesByChoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFuelHistoriesByChoiceResponse) ProtoMessage() {}

func (x *GetFuelHistoriesByChoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fuels_protos_fuel_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFuelHistoriesByChoiceResponse.ProtoReflect.Descriptor instead.
func (*GetFuelHistoriesByChoiceResponse) Descriptor() ([]byte, []int) {
	return file_protos_fuels_protos_fuel_proto_rawDescGZIP(), []int{14}
}

func (x *GetFuelHistoriesByChoiceResponse) GetFuelHistories() []*FuelHistory {
	if x != nil {
		return x.FuelHistories
	}
	return nil
}

type GetFuelHistoriesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FuelHistories []*FuelHistory `protobuf:"bytes,1,rep,name=fuel_histories,json=fuelHistories,proto3" json:"fuel_histories,omitempty"`
}

func (x *GetFuelHistoriesResponse) Reset() {
	*x = GetFuelHistoriesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_fuels_protos_fuel_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFuelHistoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFuelHistoriesResponse) ProtoMessage() {}

func (x *GetFuelHistoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fuels_protos_fuel_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFuelHistoriesResponse.ProtoReflect.Descriptor instead.
func (*GetFuelHistoriesResponse) Descriptor() ([]byte, []int) {
	return file_protos_fuels_protos_fuel_proto_rawDescGZIP(), []int{15}
}

func (x *GetFuelHistoriesResponse) GetFuelHistories() []*FuelHistory {
	if x != nil {
		return x.FuelHistories
	}
	return nil
}

type GetFuelHistoriesByDateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *GetFuelHistoriesByDateRequest) Reset() {
	*x = GetFuelHistoriesByDateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_fuels_protos_fuel_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFuelHistoriesByDateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFuelHistoriesByDateRequest) ProtoMessage() {}

func (x *GetFuelHistoriesByDateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fuels_protos_fuel_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFuelHistoriesByDateRequest.ProtoReflect.Descriptor instead.
func (*GetFuelHistoriesByDateRequest) Descriptor() ([]byte, []int) {
	return file_protos_fuels_protos_fuel_proto_rawDescGZIP(), []int{16}
}

func (x *GetFuelHistoriesByDateRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type GetFuelHistoriesByDateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FuelHistories []*FuelHistory `protobuf:"bytes,1,rep,name=fuel_histories,json=fuelHistories,proto3" json:"fuel_histories,omitempty"`
}

func (x *GetFuelHistoriesByDateResponse) Reset() {
	*x = GetFuelHistoriesByDateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_fuels_protos_fuel_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFuelHistoriesByDateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFuelHistoriesByDateResponse) ProtoMessage() {}

func (x *GetFuelHistoriesByDateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fuels_protos_fuel_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFuelHistoriesByDateResponse.ProtoReflect.Descriptor instead.
func (*GetFuelHistoriesByDateResponse) Descriptor() ([]byte, []int) {
	return file_protos_fuels_protos_fuel_proto_rawDescGZIP(), []int{17}
}

func (x *GetFuelHistoriesByDateResponse) GetFuelHistories() []*FuelHistory {
	if x != nil {
		return x.FuelHistories
	}
	return nil
}

type FuelHistoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FuelHistory *FuelHistory `protobuf:"bytes,1,opt,name=fuel_history,json=fuelHistory,proto3" json:"fuel_history,omitempty"`
}

func (x *FuelHistoryResponse) Reset() {
	*x = FuelHistoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_fuels_protos_fuel_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FuelHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuelHistoryResponse) ProtoMessage() {}

func (x *FuelHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fuels_protos_fuel_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuelHistoryResponse.ProtoReflect.Descriptor instead.
func (*FuelHistoryResponse) Descriptor() ([]byte, []int) {
	return file_protos_fuels_protos_fuel_proto_rawDescGZIP(), []int{18}
}

func (x *FuelHistoryResponse) GetFuelHistory() *FuelHistory {
	if x != nil {
		return x.FuelHistory
	}
	return nil
}

type DeleteFuelHistoriesByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteFuelHistoriesByIdRequest) Reset() {
	*x = DeleteFuelHistoriesByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_fuels_protos_fuel_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFuelHistoriesByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFuelHistoriesByIdRequest) ProtoMessage() {}

func (x *DeleteFuelHistoriesByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fuels_protos_fuel_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFuelHistoriesByIdRequest.ProtoReflect.Descriptor instead.
func (*DeleteFuelHistoriesByIdRequest) Descriptor() ([]byte, []int) {
	return file_protos_fuels_protos_fuel_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteFuelHistoriesByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_fuels_protos_fuel_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_protos_fuels_protos_fuel_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_protos_fuels_protos_fuel_proto_rawDescGZIP(), []int{20}
}

var File_protos_fuels_protos_fuel_proto protoreflect.FileDescriptor

var file_protos_fuels_protos_fuel_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x66, 0x75, 0x65, 0x6c, 0x73, 0x5f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x66, 0x75, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x7b, 0x0a, 0x04, 0x46, 0x75, 0x65, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x1f, 0x0a, 0x0b,
	0x6c, 0x61, 0x73, 0x74, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x22, 0x96, 0x01,
	0x0a, 0x0b, 0x46, 0x75, 0x65, 0x6c, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x66, 0x75, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x66, 0x75, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b,
	0x0a, 0x09, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x10, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x57, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x46, 0x75, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22,
	0x20, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x46, 0x75, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x67, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x75, 0x65, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x23, 0x0a, 0x11, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x46, 0x75, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x4b, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x46, 0x75, 0x65, 0x6c, 0x73, 0x42, 0x79, 0x43, 0x68, 0x6f,
	0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x68,
	0x6f, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x68, 0x6f, 0x69,
	0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x37, 0x0a, 0x18,
	0x47, 0x65, 0x74, 0x46, 0x75, 0x65, 0x6c, 0x73, 0x42, 0x79, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x05, 0x66, 0x75, 0x65, 0x6c,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x46, 0x75, 0x65, 0x6c, 0x52, 0x05,
	0x66, 0x75, 0x65, 0x6c, 0x73, 0x22, 0x2f, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x46, 0x75, 0x65, 0x6c,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x05, 0x66, 0x75, 0x65,
	0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x46, 0x75, 0x65, 0x6c, 0x52,
	0x05, 0x66, 0x75, 0x65, 0x6c, 0x73, 0x22, 0x29, 0x0a, 0x0c, 0x46, 0x75, 0x65, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x04, 0x66, 0x75, 0x65, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x46, 0x75, 0x65, 0x6c, 0x52, 0x04, 0x66, 0x75, 0x65,
	0x6c, 0x22, 0x68, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x75, 0x65, 0x6c, 0x48,
	0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x66, 0x75, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x66, 0x75, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b,
	0x0a, 0x09, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x72, 0x49, 0x64, 0x22, 0x2d, 0x0a, 0x1b, 0x47,
	0x65, 0x74, 0x46, 0x75, 0x65, 0x6c, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x42,
	0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x53, 0x0a, 0x1c, 0x47, 0x65,
	0x74, 0x46, 0x75, 0x65, 0x6c, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x42, 0x79,
	0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x0e, 0x66, 0x75,
	0x65, 0x6c, 0x5f, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x46, 0x75, 0x65, 0x6c, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79,
	0x52, 0x0d, 0x66, 0x75, 0x65, 0x6c, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x22,
	0x53, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x46, 0x75, 0x65, 0x6c, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72,
	0x69, 0x65, 0x73, 0x42, 0x79, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x63, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x57, 0x0a, 0x20, 0x47, 0x65, 0x74, 0x46, 0x75, 0x65, 0x6c, 0x48,
	0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x42, 0x79, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x0e, 0x66, 0x75, 0x65, 0x6c,
	0x5f, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x46, 0x75, 0x65, 0x6c, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x0d,
	0x66, 0x75, 0x65, 0x6c, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x22, 0x4f, 0x0a,
	0x18, 0x47, 0x65, 0x74, 0x46, 0x75, 0x65, 0x6c, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x0e, 0x66, 0x75, 0x65,
	0x6c, 0x5f, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x46, 0x75, 0x65, 0x6c, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52,
	0x0d, 0x66, 0x75, 0x65, 0x6c, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x22, 0x33,
	0x0a, 0x1d, 0x47, 0x65, 0x74, 0x46, 0x75, 0x65, 0x6c, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69,
	0x65, 0x73, 0x42, 0x79, 0x44, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x65, 0x22, 0x55, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x46, 0x75, 0x65, 0x6c, 0x48, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x42, 0x79, 0x44, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x0e, 0x66, 0x75, 0x65, 0x6c, 0x5f, 0x68, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x46, 0x75, 0x65, 0x6c, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x0d, 0x66, 0x75, 0x65,
	0x6c, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x22, 0x46, 0x0a, 0x13, 0x46, 0x75,
	0x65, 0x6c, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2f, 0x0a, 0x0c, 0x66, 0x75, 0x65, 0x6c, 0x5f, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x46, 0x75, 0x65, 0x6c, 0x48, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x0b, 0x66, 0x75, 0x65, 0x6c, 0x48, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x22, 0x30, 0x0a, 0x1e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x75, 0x65, 0x6c,
	0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32, 0x85, 0x06,
	0x0a, 0x0b, 0x46, 0x75, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2f, 0x0a,
	0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x75, 0x65, 0x6c, 0x12, 0x12, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x46, 0x75, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x0d, 0x2e, 0x46, 0x75, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29,
	0x0a, 0x07, 0x47, 0x65, 0x74, 0x46, 0x75, 0x65, 0x6c, 0x12, 0x0f, 0x2e, 0x47, 0x65, 0x74, 0x46,
	0x75, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x46, 0x75, 0x65,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x0a, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x46, 0x75, 0x65, 0x6c, 0x12, 0x12, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x46, 0x75, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x46, 0x75,
	0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x0a, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x46, 0x75, 0x65, 0x6c, 0x12, 0x12, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x46, 0x75, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x06, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x12, 0x46, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x46, 0x75, 0x65, 0x6c, 0x42,
	0x79, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x12, 0x18, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x75, 0x65,
	0x6c, 0x73, 0x42, 0x79, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x19, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x75, 0x65, 0x6c, 0x73, 0x42, 0x79, 0x43, 0x68,
	0x6f, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x08,
	0x47, 0x65, 0x74, 0x46, 0x75, 0x65, 0x6c, 0x73, 0x12, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x11, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x75, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x75, 0x65,
	0x6c, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x19, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x46, 0x75, 0x65, 0x6c, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x46, 0x75, 0x65, 0x6c, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x14, 0x47, 0x65, 0x74,
	0x46, 0x75, 0x65, 0x6c, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x42, 0x79, 0x49,
	0x44, 0x12, 0x1c, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x75, 0x65, 0x6c, 0x48, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x69, 0x65, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1d, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x75, 0x65, 0x6c, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69,
	0x65, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42,
	0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x75, 0x65, 0x6c, 0x48, 0x69, 0x73, 0x74,
	0x6f, 0x72, 0x69, 0x65, 0x73, 0x42, 0x79, 0x49, 0x44, 0x12, 0x1f, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x46, 0x75, 0x65, 0x6c, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x42,
	0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x06, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x12, 0x5f, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x46, 0x75, 0x65, 0x6c, 0x48, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x42, 0x79, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x12, 0x20,
	0x2e, 0x47, 0x65, 0x74, 0x46, 0x75, 0x65, 0x6c, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x65,
	0x73, 0x42, 0x79, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x21, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x75, 0x65, 0x6c, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72,
	0x69, 0x65, 0x73, 0x42, 0x79, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x59, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x46, 0x75, 0x65, 0x6c, 0x48, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x42, 0x79, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x2e,
	0x47, 0x65, 0x74, 0x46, 0x75, 0x65, 0x6c, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73,
	0x42, 0x79, 0x44, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e,
	0x47, 0x65, 0x74, 0x46, 0x75, 0x65, 0x6c, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73,
	0x42, 0x79, 0x44, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35,
	0x0a, 0x10, 0x47, 0x65, 0x74, 0x46, 0x75, 0x65, 0x6c, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69,
	0x65, 0x73, 0x12, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x19, 0x2e, 0x47, 0x65, 0x74,
	0x46, 0x75, 0x65, 0x6c, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_fuels_protos_fuel_proto_rawDescOnce sync.Once
	file_protos_fuels_protos_fuel_proto_rawDescData = file_protos_fuels_protos_fuel_proto_rawDesc
)

func file_protos_fuels_protos_fuel_proto_rawDescGZIP() []byte {
	file_protos_fuels_protos_fuel_proto_rawDescOnce.Do(func() {
		file_protos_fuels_protos_fuel_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_fuels_protos_fuel_proto_rawDescData)
	})
	return file_protos_fuels_protos_fuel_proto_rawDescData
}

var file_protos_fuels_protos_fuel_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_protos_fuels_protos_fuel_proto_goTypes = []any{
	(*Fuel)(nil),                             // 0: Fuel
	(*FuelHistory)(nil),                      // 1: FuelHistory
	(*CreateFuelRequest)(nil),                // 2: CreateFuelRequest
	(*GetFuelRequest)(nil),                   // 3: GetFuelRequest
	(*UpdateFuelRequest)(nil),                // 4: UpdateFuelRequest
	(*DeleteFuelRequest)(nil),                // 5: DeleteFuelRequest
	(*GetFuelsByChoiceRequest)(nil),          // 6: GetFuelsByChoiceRequest
	(*GetFuelsByChoiceResponse)(nil),         // 7: GetFuelsByChoiceResponse
	(*GetFuelsResponse)(nil),                 // 8: GetFuelsResponse
	(*FuelResponse)(nil),                     // 9: FuelResponse
	(*CreateFuelHistoryRequest)(nil),         // 10: CreateFuelHistoryRequest
	(*GetFuelHistoriesByIdRequest)(nil),      // 11: GetFuelHistoriesByIdRequest
	(*GetFuelHistoriesByIdResponse)(nil),     // 12: GetFuelHistoriesByIdResponse
	(*GetFuelHistoriesByChoiceRequest)(nil),  // 13: GetFuelHistoriesByChoiceRequest
	(*GetFuelHistoriesByChoiceResponse)(nil), // 14: GetFuelHistoriesByChoiceResponse
	(*GetFuelHistoriesResponse)(nil),         // 15: GetFuelHistoriesResponse
	(*GetFuelHistoriesByDateRequest)(nil),    // 16: GetFuelHistoriesByDateRequest
	(*GetFuelHistoriesByDateResponse)(nil),   // 17: GetFuelHistoriesByDateResponse
	(*FuelHistoryResponse)(nil),              // 18: FuelHistoryResponse
	(*DeleteFuelHistoriesByIdRequest)(nil),   // 19: DeleteFuelHistoriesByIdRequest
	(*Empty)(nil),                            // 20: Empty
}
var file_protos_fuels_protos_fuel_proto_depIdxs = []int32{
	0,  // 0: GetFuelsByChoiceResponse.fuels:type_name -> Fuel
	0,  // 1: GetFuelsResponse.fuels:type_name -> Fuel
	0,  // 2: FuelResponse.fuel:type_name -> Fuel
	1,  // 3: GetFuelHistoriesByIdResponse.fuel_histories:type_name -> FuelHistory
	1,  // 4: GetFuelHistoriesByChoiceResponse.fuel_histories:type_name -> FuelHistory
	1,  // 5: GetFuelHistoriesResponse.fuel_histories:type_name -> FuelHistory
	1,  // 6: GetFuelHistoriesByDateResponse.fuel_histories:type_name -> FuelHistory
	1,  // 7: FuelHistoryResponse.fuel_history:type_name -> FuelHistory
	2,  // 8: FuelService.CreateFuel:input_type -> CreateFuelRequest
	3,  // 9: FuelService.GetFuel:input_type -> GetFuelRequest
	4,  // 10: FuelService.UpdateFuel:input_type -> UpdateFuelRequest
	5,  // 11: FuelService.DeleteFuel:input_type -> DeleteFuelRequest
	6,  // 12: FuelService.GetFuelByChoice:input_type -> GetFuelsByChoiceRequest
	20, // 13: FuelService.GetFuels:input_type -> Empty
	10, // 14: FuelService.CreateFuelHistory:input_type -> CreateFuelHistoryRequest
	11, // 15: FuelService.GetFuelHistoriesByID:input_type -> GetFuelHistoriesByIdRequest
	19, // 16: FuelService.DeleteFuelHistoriesByID:input_type -> DeleteFuelHistoriesByIdRequest
	13, // 17: FuelService.GetFuelHistoriesByChoice:input_type -> GetFuelHistoriesByChoiceRequest
	16, // 18: FuelService.GetFuelHistoriesByDate:input_type -> GetFuelHistoriesByDateRequest
	20, // 19: FuelService.GetFuelHistories:input_type -> Empty
	9,  // 20: FuelService.CreateFuel:output_type -> FuelResponse
	9,  // 21: FuelService.GetFuel:output_type -> FuelResponse
	9,  // 22: FuelService.UpdateFuel:output_type -> FuelResponse
	20, // 23: FuelService.DeleteFuel:output_type -> Empty
	7,  // 24: FuelService.GetFuelByChoice:output_type -> GetFuelsByChoiceResponse
	8,  // 25: FuelService.GetFuels:output_type -> GetFuelsResponse
	18, // 26: FuelService.CreateFuelHistory:output_type -> FuelHistoryResponse
	12, // 27: FuelService.GetFuelHistoriesByID:output_type -> GetFuelHistoriesByIdResponse
	20, // 28: FuelService.DeleteFuelHistoriesByID:output_type -> Empty
	14, // 29: FuelService.GetFuelHistoriesByChoice:output_type -> GetFuelHistoriesByChoiceResponse
	17, // 30: FuelService.GetFuelHistoriesByDate:output_type -> GetFuelHistoriesByDateResponse
	15, // 31: FuelService.GetFuelHistories:output_type -> GetFuelHistoriesResponse
	20, // [20:32] is the sub-list for method output_type
	8,  // [8:20] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_protos_fuels_protos_fuel_proto_init() }
func file_protos_fuels_protos_fuel_proto_init() {
	if File_protos_fuels_protos_fuel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_fuels_protos_fuel_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Fuel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_fuels_protos_fuel_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*FuelHistory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_fuels_protos_fuel_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CreateFuelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_fuels_protos_fuel_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetFuelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_fuels_protos_fuel_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateFuelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_fuels_protos_fuel_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteFuelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_fuels_protos_fuel_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetFuelsByChoiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_fuels_protos_fuel_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetFuelsByChoiceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_fuels_protos_fuel_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*GetFuelsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_fuels_protos_fuel_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*FuelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_fuels_protos_fuel_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*CreateFuelHistoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_fuels_protos_fuel_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*GetFuelHistoriesByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_fuels_protos_fuel_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*GetFuelHistoriesByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_fuels_protos_fuel_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*GetFuelHistoriesByChoiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_fuels_protos_fuel_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*GetFuelHistoriesByChoiceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_fuels_protos_fuel_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*GetFuelHistoriesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_fuels_protos_fuel_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*GetFuelHistoriesByDateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_fuels_protos_fuel_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*GetFuelHistoriesByDateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_fuels_protos_fuel_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*FuelHistoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_fuels_protos_fuel_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteFuelHistoriesByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_fuels_protos_fuel_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_fuels_protos_fuel_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_fuels_protos_fuel_proto_goTypes,
		DependencyIndexes: file_protos_fuels_protos_fuel_proto_depIdxs,
		MessageInfos:      file_protos_fuels_protos_fuel_proto_msgTypes,
	}.Build()
	File_protos_fuels_protos_fuel_proto = out.File
	file_protos_fuels_protos_fuel_proto_rawDesc = nil
	file_protos_fuels_protos_fuel_proto_goTypes = nil
	file_protos_fuels_protos_fuel_proto_depIdxs = nil
}
